name: Nalettes
description: A repository of color palettes picked up carefully, inspired from nature.

category-list:
tag-list: 

footer-links:
  dribbble:
  email: guyswhocode@gmail.com
  facebook: guyswhocode
  flickr:
  github: guyswhocode
  instagram: guyswhocode
  linkedin: guyswhocode
  pinterest: guyswhocode
  twitter: guyswhoc0de


disqus: guyswhocode
url: http://www.guyswhocode.com

baseurl: "http://guyswhocode.github.io/nalettes"
permalink: /:title

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME